Server/Manager/Manager/Manager.Painel/Models/Empresa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Painel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Usuarios = new HashSet<Usuario>();
            this.ClienteTipoes = new HashSet<ClienteTipo>();
            this.Clientes = new HashSet<Cliente>();
            this.Marcas = new HashSet<Marca>();
            this.Produtoes = new HashSet<Produto>();
            this.OrdemServicoes = new HashSet<OrdemServico>();
            this.AcessoWebs = new HashSet<AcessoWeb>();
            this.Instagrams = new HashSet<Instagram>();
        }
    
        public int Codigo { get; set; }
        public string NomeEmpresa { get; set; }
        public string Cnpj { get; set; }
        public string Endereco { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Cep { get; set; }
        public string Estado { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Responsavel { get; set; }
        public string Site { get; set; }
        public Nullable<System.DateTime> DtCadastro { get; set; }
        public bool Liberado { get; set; }
        public bool Master { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public virtual ICollection<ClienteTipo> ClienteTipoes { get; set; }
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<Marca> Marcas { get; set; }
        public virtual Ponteiro Ponteiro { get; set; }
        public virtual ICollection<Produto> Produtoes { get; set; }
        public virtual ICollection<OrdemServico> OrdemServicoes { get; set; }
        public virtual ICollection<AcessoWeb> AcessoWebs { get; set; }
        public virtual ICollection<Instagram> Instagrams { get; set; }
    }
}

Server/Manager/Manager/Manager.Painel/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Manager.Painel.Models;

namespace Manager.Painel.Controllers
{
    public class EmpresaController : BaseController
    {
        private db_Entities db = new db_Entities();

        //
        // GET: /Empresa/

        public ActionResult Index()
        {
            int codigoEmpresa = Context.getCodigoEmpresa();
            var empresas = db.Empresas.Where(e => e.Codigo == codigoEmpresa).FirstOrDefault();

            #region uf
            var ufs = new List<SelectListItem>();
            ufs.Add(new SelectListItem() { Text = "<selecione>", Value = "" });
            foreach (var item in Context.getEstados())
            {
                ufs.Add(new SelectListItem() { Text = item.nome, Value = item.sigla });
            }

            if (empresas.Codigo == 0)
                ViewBag.Estado = new SelectList(ufs, "Value", "Text", "");
            else
                ViewBag.Estado = new SelectList(ufs, "Value", "Text", empresas.Estado);
            #endregion

            return View(empresas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empresa).State = EntityState.Modified;
                db.SaveChanges();

                ViewBag.mensagem = "Empresa atualizada com sucesso";

                return RedirectToAction("Index");
            }
            ViewBag.Codigo = new SelectList(db.Ponteiroes, "CodigoEmpresa", "CodigoEmpresa", empresa.Codigo);
            return View(empresa);
        }

        //
        // GET: /Empresa/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Empresa empresa = db.Empresas.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        //
        // POST: /Empresa/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empresa empresa = db.Empresas.Find(id);
            db.Empresas.Remove(empresa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Server/Manager/Manager/Manager.Painel/Views/Empresa/Cadastrar.cshtml
@model Manager.Painel.Models.Empresa

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Empresa</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Codigo, "Ponteiro")
        </div>
        <div class="editor-field">
            @Html.DropDownList("Codigo", String.Empty)
            @Html.ValidationMessageFor(model => model.Codigo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NomeEmpresa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NomeEmpresa)
            @Html.ValidationMessageFor(model => model.NomeEmpresa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cnpj)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cnpj)
            @Html.ValidationMessageFor(model => model.Cnpj)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Endereco)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Endereco)
            @Html.ValidationMessageFor(model => model.Endereco)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Complemento)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Complemento)
            @Html.ValidationMessageFor(model => model.Complemento)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Bairro)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Bairro)
            @Html.ValidationMessageFor(model => model.Bairro)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cidade)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cidade)
            @Html.ValidationMessageFor(model => model.Cidade)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cep)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cep)
            @Html.ValidationMessageFor(model => model.Cep)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Estado)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Estado)
            @Html.ValidationMessageFor(model => model.Estado)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Telefone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Telefone)
            @Html.ValidationMessageFor(model => model.Telefone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Celular)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Celular)
            @Html.ValidationMessageFor(model => model.Celular)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Responsavel)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Responsavel)
            @Html.ValidationMessageFor(model => model.Responsavel)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Site)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Site)
            @Html.ValidationMessageFor(model => model.Site)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DtCadastro)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DtCadastro)
            @Html.ValidationMessageFor(model => model.DtCadastro)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Liberado)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Liberado)
            @Html.ValidationMessageFor(model => model.Liberado)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Master)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Master)
            @Html.ValidationMessageFor(model => model.Master)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Server/Manager/Manager/Manager.Painel/Views/Empresa/Edit.cshtml
@model Manager.Painel.Models.Empresa

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Empresa</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Codigo, "Ponteiro")
        </div>
        <div class="editor-field">
            @Html.DropDownList("Codigo", String.Empty)
            @Html.ValidationMessageFor(model => model.Codigo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NomeEmpresa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NomeEmpresa)
            @Html.ValidationMessageFor(model => model.NomeEmpresa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cnpj)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cnpj)
            @Html.ValidationMessageFor(model => model.Cnpj)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Endereco)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Endereco)
            @Html.ValidationMessageFor(model => model.Endereco)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Complemento)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Complemento)
            @Html.ValidationMessageFor(model => model.Complemento)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Bairro)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Bairro)
            @Html.ValidationMessageFor(model => model.Bairro)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cidade)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cidade)
            @Html.ValidationMessageFor(model => model.Cidade)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cep)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cep)
            @Html.ValidationMessageFor(model => model.Cep)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Estado)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Estado)
            @Html.ValidationMessageFor(model => model.Estado)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Telefone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Telefone)
            @Html.ValidationMessageFor(model => model.Telefone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Celular)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Celular)
            @Html.ValidationMessageFor(model => model.Celular)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Responsavel)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Responsavel)
            @Html.ValidationMessageFor(model => model.Responsavel)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Site)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Site)
            @Html.ValidationMessageFor(model => model.Site)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DtCadastro)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DtCadastro)
            @Html.ValidationMessageFor(model => model.DtCadastro)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Liberado)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Liberado)
            @Html.ValidationMessageFor(model => model.Liberado)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Master)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Master)
            @Html.ValidationMessageFor(model => model.Master)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Server/Manager/Manager/Manager.Painel/Views/Empresa/Index.cshtml
@model Manager.Painel.Models.Empresa

@{
    ViewBag.Title = "Cadastro da Empresa";
    ViewBag.Subtitle = "Manutenção dos dados empresa";
    Layout = "~/Views/masterPage.cshtml";
}

<fieldset>
    @using (Html.BeginForm("Edit", "Empresa", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container" style="overflow: auto;">
            @Html.HiddenFor(model => model.Codigo)
            <div class="row">
                <div class="col-lg-6">
                    Empresa:<br />
                    <input type="text" id="NomeEmpresa" name="NomeEmpresa" style="width:100%" class="form-control validar notnull" value="@Model.NomeEmpresa">
                </div>
                <div class="col-lg-4">
                    CNPJ:<br />
                    <input type="text" id="Cnpj" name="Cnpj" style="width:100%" class="form-control" value="@Model.Cnpj">
                </div>
            </div>
            <div class="row" style="margin-top:20px">
                <div class="col-lg-4">
                    Endereço:<br />
                    <input type="text" id="Endereco" name="Endereco" style="width:100%" class="form-control" value="@Model.Endereco">
                </div>
                <div class="col-lg-2">
                    Complemento:<br />
                    <input type="text" id="Complemento" name="Complemento" style="width:100%" class="form-control" value="@Model.Complemento">
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-lg-3">
                    Bairro:<br />
                    <input type="text" id="Bairro" name="Bairro" style="width:100%" class="form-control" value="@Model.Bairro">
                </div>
                <div class="col-lg-3">
                    Cidade:<br />
                    <input type="text" id="Cidade" name="Cidade" style="width:100%" class="form-control" value="@Model.Cidade">
                </div>
                <div class="col-lg-1">
                    CEP:<br />
                    <input type="text" id="Cep" name="Cep" style="width:100%" mask="cep" class="form-control" value="@Model.Cep">
                </div>
                <div class="col-lg-2">
                    UF:<br />
                    @Html.DropDownList("Estado", null, new { @class = "form-control" })
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-lg-3">
                    Telefone:<br />
                    <input type="text" id="Telefone" name="Telefone" style="width:100%" mask="telefone" class="form-control" value="@Model.Telefone">
                </div>
                <div class="col-lg-3">
                    Celular:<br />
                    <input type="text" id="Celular" name="Celular" style="width:100%" mask="celular" class="form-control" value="@Model.Celular">
                </div>
                <div class="col-lg-3">
                    Email:<br />
                    <input type="text" id="Email" name="Email" style="width:100%" class="form-control validar email" value="@Model.Email">
                </div>
                <div class="col-lg-3">
                    Responsável:<br />
                    <input type="text" id="Responsavel" name="Responsavel" style="width:100%" class="form-control" value="@Model.Responsavel">
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-lg-6">
                    Site:<br />
                    <input type="text" id="Site" name="Site" style="width:100%" class="form-control" value="@Model.Site">
                </div>
            </div>
            <div class="row" style="margin-top:20px">
                <div class="col-lg-6">
                    <button type="submit" class="btn btn-success" style="width:103px; float:right">Salvar&nbsp;&nbsp;&nbsp;<i class="fa fa-save"></i></button>
                </div>
                <div class="col-lg-6">
                    <a href="javascript:;" onclick="javascript:bootbox.hideAll();" class="btn btn-danger" style="width: 103px; float: left">
                        Cancelar&nbsp;&nbsp;&nbsp;<i class="fa fa-undo"></i>
                    </a>
                </div>
            </div>
        </div>
    }
</fieldset>